[project]
name = "reline"
version = "0.1.0"
description = "Pipeline tool for upscale manga"
authors = [{ name = "Sekiju" }, { name = "umzi" }]
requires-python = ">=3.10"
dependencies = ["pepeline", "chainner_ext", "tqdm", "numpy"]

[system-requirements]
cuda = "12.1"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]
conda-pypi-map = { "pytorch" = "https://public.yor.ovh/pytorch_mapping.json" }

[tool.pixi.dependencies]
tqdm = { version = "4.66.4" }
numpy = ">=2.0.0,<2.1"
opencv = { version = ">=4.10,<4.11", channel = "conda-forge" }

[tool.pixi.pypi-dependencies]
reline = { path = ".", editable = true }
# todo: move to `project.dependencies` / create self-hosted repo
resselt = { url = "https://public.yor.ovh/resselt-0.1.0-py3-none-any.whl" }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev", "torch-cuda"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }

[tool.pixi.feature.torch-cuda]
channels = ["nvidia/label/cuda-12.1.0", {channel = "nvidia", priority = 1}, "pytorch", "conda-forge"]

[tool.pixi.feature.torch-cuda.dependencies]
cuda = {version = "*", channel="nvidia/label/cuda-12.1.0"}
pytorch = { version = ">=2.3.0,<2.4", channel = "pytorch" }
torchvision = { version = ">=0.18.0,<0.19", channel = "pytorch" }
pytorch-cuda = { version = "12.1.*", channel = "pytorch" }

[tool.pixi.feature.dev.dependencies]
pixi-pycharm = ">=0.0.5,<0.1"
ruff = ">=0.5.0,<0.6"
pre-commit = ">=3.7.1,<3.8"
requests = ">=2.32.3,<2.33"
pytest = ">=7.2.0,<7.3"

[tool.pixi.feature.build.tasks]
build = "python -m build --no-isolation --wheel ."

[tool.pixi.feature.build.dependencies]
build = "*"
pdm-backend = "*"
