[project]
name = "reline"
version = "0.1.0"
description = "Pipeline tool for upscale manga"
authors = [{ name = "Sekiju" }, { name = "umzi" }]
requires-python = ">=3.10"
dependencies = ["pepeline", "chainner_ext", "tqdm"]

[system-requirements]
cuda = "12.1"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tool.pixi.dependencies]
tqdm = { version = "4.66.4" }
numpy = ">=2.0.0,<2.1"

[tool.pixi.pypi-dependencies]
reline = { path = ".", editable = true }
# todo: move to `project.dependencies` / create self-hosted repo
resselt = { url = "https://public.yor.ovh/resselt-0.1.0-py3-none-any.whl" }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }

[tool.pixi.feature.dev.dependencies]
pixi-pycharm = ">=0.0.5,<0.1"
ruff = ">=0.5.0,<0.6"
pre-commit = ">=3.7.1,<3.8"

[tool.pixi.feature.build.tasks]
build = "python -m build --no-isolation --wheel ."

[tool.pixi.feature.build.dependencies]
build = "*"
pdm-backend = "*"
