[project]
name = "reline"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "chainner-ext>=0.3.10",
    "moviepy==1.0.2",
    "opencv-python-headless>=4.11.0.86",
    "orjson>=3.10.15",
    "pepeline>=0.3.14",
    "resselt<2",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.4",
    "typer>=0.15.1",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
resselt = { index = "yor" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "yor"
url = "https://pypi.yor.ovh/simple/"
publish-url = "https://pypi.yor.ovh/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
