[tool.poetry]
name = "reline"
version = "1.0.0"
description = "Pipeline for process images"
authors = ["Sekiju", "umzi"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10"
pepeline = "^0.3.8"
chainner-ext = "^0.3.10"
tqdm = "^4.66.4"
opencv-python = "^4.10.0.84"
resselt = {url = "https://public.yor.ovh/resselt-1.0.0-py3-none-any.whl"}
numpy = "<2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.5"
pre-commit = "^3.8.0"

[tool.poetry.group.torch.dependencies]
torch = {version = "^2.4.0+cu121", source = "pytorch-gpu"}
torchvision = {version = "^0.19.0+cu121", source = "pytorch-gpu"}

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.ruff]
line-length = 150
target-version = "py310"

[tool.ruff.format]
quote-style = "single"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"